### PR TITLE
Added YML file for GitHub Actions

### PR DESCRIPTION
**Pull request by dragos5436**

### CODE REVIEW

**Review by opitz — CHANGES_REQUESTED** [review]
cannot delete this methinks...

**Review by opitz — CHANGES_REQUESTED** [review]
Please amend the commit with the Jira code.
https://www.atlassian.com/git/tutorials/rewriting-history

**Review by opitz — APPROVED** [review]
All good.

**Review by opitz — APPROVED** [review]
Still good.

**Comment by opitz** [comment]
Just notices this is an old request? It will have to be closed methinks..?! (I cannot do this)

**Review by opitz — APPROVED** [review]
OK

**Review by opitz — APPROVED** [review]
All good.

**Comment by aspark21** [comment]
going to add with an updated matrix

**Pull request closed without merging**
